# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCitationCFF: false
AddCodeOfConduct: false
AddContributionDocs: false
AddCopierCI: false
AddDocs: true
AddDocsCI: true
AddFormatterAndLinterConfigFiles: true
AddGitHubPRTemplate: true
AddGitHubTemplates: false
AddLintCI: false
AddLychee: true
AddMacToCI: true
AddPrecommit: true
AddPrecommitUpdateCI: false
AddTagBotCI: true
AddTestCI: true
AddWinToCI: false
Authors: 'Katharina Kormann <k.kormann@rub.de>, Pierre Navaro <navaro@math.cnrs.fr>,
    Klaus Reuter <khr@mpcdf.mpg.de> '
CheckExplicitImports: false
ConfigIndentation: 2
GitHubActionVersionAutoUpdate: dependabot
JuliaCompatAutoUpdate: compathelper
JuliaIndentation: 4
JuliaMinCIVersion: lts
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Katharina Kormann, Pierre Navaro, Klaus Reuter
MarkdownIndentation: 2
PackageName: PeriodicInterpolation1D
PackageOwner: juliavlasov
PackageUUID: d32cb302-a956-591b-8d53-254f0a948d40
RunJuliaNightlyOnCI: false
StrategyConfirmIncluded: true
StrategyLevel: 1
StrategyReviewExcluded: true
TestingStrategy: testitem_basic
UseCirrusCI: false
_src_path: /Users/navaro/.julia/packages/BestieTemplate/fOzc4
